import {
  Baby,
  Banknote,
  Beer,
  Bike,
  Book,
  Briefcase,
  Bus,
  Car,
  Clapperboard,
  Coffee,
  CreditCard,
  Dumbbell,
  Ellipsis,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HandCoins,
  Heart,
  HeartPulse,
  House,
  Landmark,
  Laptop,
  Music,
  PawPrint,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Receipt,
  Repeat,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Train,
  TrendingUp,
  Tv,
  Umbrella,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  'shopping-cart': ShoppingCart,
  utensils: Utensils,
  coffee: Coffee,
  pizza: Pizza,
  beer: Beer,
  bus: Bus,
  car: Car,
  fuel: Fuel,
  bike: Bike,
  train: Train,
  plane: Plane,
  house: House,
  zap: Zap,
  wifi: Wifi,
  smartphone: Smartphone,
  tv: Tv,
  wrench: Wrench,
  'heart-pulse': HeartPulse,
  pill: Pill,
  dumbbell: Dumbbell,
  scissors: Scissors,
  'graduation-cap': GraduationCap,
  book: Book,
  clapperboard: Clapperboard,
  music: Music,
  'gamepad-2': Gamepad2,
  'shopping-bag': ShoppingBag,
  shirt: Shirt,
  gift: Gift,
  heart: Heart,
  'paw-print': PawPrint,
  baby: Baby,
  sparkles: Sparkles,
  umbrella: Umbrella,
  repeat: Repeat,
  receipt: Receipt,
  'credit-card': CreditCard,
  landmark: Landmark,
  briefcase: Briefcase,
  laptop: Laptop,
  'trending-up': TrendingUp,
  banknote: Banknote,
  'hand-coins': HandCoins,
  'piggy-bank': PiggyBank,
  wallet: Wallet,
  ellipsis: Ellipsis,
}

export const CATEGORY_ICON_KEYS = Object.keys(CATEGORY_ICONS)

export const CATEGORY_ICON_LABELS: Record<string, string> = {
  'shopping-cart': 'Carrito',
  'utensils': 'Cubiertos',
  'coffee': 'Café',
  'pizza': 'Pizza',
  'beer': 'Cerveza',
  'bus': 'Bus',
  'car': 'Carro',
  'fuel': 'Gasolina',
  'bike': 'Bicicleta',
  'train': 'Tren',
  'plane': 'Avión',
  'house': 'Casa',
  'zap': 'Energía',
  'wifi': 'Internet',
  'smartphone': 'Celular',
  'tv': 'Televisión',
  'wrench': 'Arreglos',
  'heart-pulse': 'Salud',
  'pill': 'Medicamentos',
  'dumbbell': 'Gimnasio',
  'scissors': 'Peluquería',
  'graduation-cap': 'Estudio',
  'book': 'Libros',
  'clapperboard': 'Cine',
  'music': 'Música',
  'gamepad-2': 'Juegos',
  'shopping-bag': 'Compras',
  'shirt': 'Ropa',
  'gift': 'Regalo',
  'heart': 'Corazón',
  'paw-print': 'Mascotas',
  'baby': 'Bebé',
  'sparkles': 'Cuidado personal',
  'umbrella': 'Seguros',
  'repeat': 'Suscripción',
  'receipt': 'Factura',
  'credit-card': 'Tarjeta',
  'landmark': 'Banco',
  'briefcase': 'Trabajo',
  'laptop': 'Computador',
  'trending-up': 'Inversión',
  'banknote': 'Billete',
  'hand-coins': 'Pago',
  'piggy-bank': 'Ahorro',
  'wallet': 'Billetera',
  'ellipsis': 'Otros',
}

export const CATEGORY_COLORS = [
  '#2f9e63',
  '#2b8a3e',
  '#0c8599',
  '#1c7ed6',
  '#4263eb',
  '#7048e8',
  '#ae3ec9',
  '#d6336c',
  '#e03131',
  '#e8590c',
  '#e67700',
  '#a0712b',
  '#868e96',
  '#495057',
]

export const CATEGORY_COLOR_LABELS: Record<string, string> = {
  '#2f9e63': 'Verde',
  '#2b8a3e': 'Verde oscuro',
  '#0c8599': 'Turquesa',
  '#1c7ed6': 'Azul',
  '#4263eb': 'Índigo',
  '#7048e8': 'Violeta',
  '#ae3ec9': 'Morado',
  '#d6336c': 'Rosado',
  '#e03131': 'Rojo',
  '#e8590c': 'Naranja',
  '#e67700': 'Ámbar',
  '#a0712b': 'Café',
  '#868e96': 'Gris',
  '#495057': 'Gris oscuro',
}

export function iconFor(key: string): LucideIcon {
  return CATEGORY_ICONS[key] ?? Ellipsis
}
